### ISSUE TITLE
Publish v0.0.3 to pip?

### ISSUE THREAD

**Issue by jmontrose** [felt/felt-python#14]
Any blockers for pushing to pip?

https://github.com/felt/felt-python/commit/3c6ecd462cb1f84066ce58c342166983dd3dfa08

I still see 0.2

https://pypi.org/project/felt/

I'd like to use some of the new calls in a remote deployed context, and pip would be the easiest way.

e.g. refresh_file_layer() is in the docs and code, but not available from the `pip install felt-python` version.

**Comment by arredond** [comment]
I think you're confusing this library (`felt-python`) with a different, unrelated package called `felt` (seems to be related with "flow path networks).

Here's the listing of `felt-python` on PyPi, where the latest version is v0.0.3: https://pypi.org/project/felt-python/

**Comment by jmontrose** [comment]
You are so right, thank you!  Sorry about the confusion 🙏

**Comment by jmontrose** [comment]
FYI, the real problem was missing https://github.com/felt/felt-python/blob/main/felt_python/layers.py#L215 in the pip release, but that's easy enough to work around
